neos/rector

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionContextInBackendRector.php
- src/ContentRepository90/Rules/FusionContextLiveRector.php
- src/ContentRepository90/Rules/FusionNodePathRector.php
- src/Core/FusionProcessing/EelExpressionTransformer.php
- src/Core/FusionProcessing/FusionRectorInterface.php
- src/Core/FusionProcessing/Helper/PrecedingFusionFileComment.php
- src/Core/FusionProcessing/Helper/RegexCommentTemplatePair.php
- src/Generic/Rules/FusionNodePropertyPathToWarningCommentRector.php
- src/Generic/ValueObject/FusionNodePropertyPathToWarningComment.php
- tests/ContentRepository90/Rules/FusionNodePathRector/Fixture/some_file.fusion
- tests/ContentRepository90/Rules/FusionNodePathRector/FusionNodePathRectorTest.php
- tests/ContentRepository90/Rules/FusionNodePathRector/config/configured_rule.php
- tests/Generic/Rules/FusionNodePropertyPathToWarningCommentRector/Fixture/some_file.fusion
- tests/Generic/Rules/FusionNodePropertyPathToWarningCommentRector/FusionNodePropertyPathToWarningCommentRectorTest.php
- tests/Generic/Rules/FusionNodePropertyPathToWarningCommentRector/config/configured_rule.php
Add FusionNodePathRector to transform 
`node.path`
to
`Neos.NodeInfo.path(node)`
Enhance EelExpressionTransformer to add multiple comments by multiple regular expression matches with correct line number references.
Add FusionNodePropertyPathToWarningCommentRector to add comments for
`node.foo` or `node.bar.baz`
when there is no automatic migration available.
> Add and enhance fusion rectors

- config/set/contentrepository-90.php
- docs/architecture_2022_09_16_FusionRefactorings.md
- src/ContentRepository90/Rules/FusionContextInBackendRector.php
- src/ContentRepository90/Rules/FusionContextLiveRector.php
- tests/ContentRepository90/Rules/FusionContextInBackendRector/Fixture/some_file.fusion
- tests/ContentRepository90/Rules/FusionContextLiveRector/Fixture/some_file.fusion
- Replace all usages of `Neos.Ui.NodeInfo.inBackend` in favour of `Neos.Node.inBackend`
- Replace all usages of `Neos.Ui.NodeInfo.isLive` in favour of `Neos.Node.isLive`
Relates: neos/neos-development-collection#4074
Relates: neos/neos-ui#3414
> TASK: replace `Neos.Ui.NodeInfo.inBackend` and `Neos.Ui.NodeInfo.isLive` with correct eel helper

- src/ContentRepository90/Rules/FusionContextInBackendRector.php
- src/ContentRepository90/Rules/FusionContextLiveRector.php
- tests/ContentRepository90/Rules/FusionContextInBackendRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionContextLiveRector/Fixture/some_file.fusion.inc
the migration previously adjusted the code to a now deprecated eel helper. In pr https://github.com/neos/neos-development-collection/pull/4505 the userInterfaceMode is introduced as global fusionValue which made an adjustment in the rector necessary.
`(node|documentNode|site).context.inBackend` is now migrated to `userInterfaceMode.isEdit` `(node|documentNode|site).context.live` is now migrated to `userInterfaceMode.isLive`
In cases where it cannot be determined wether a node is affected by the `context` operation a comment is added as before.
Relates: https://github.com/neos/neos-development-collection/issues/4086
> TASK: Adjust migration for user interface mode

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeTypeNameRector.php
- src/ContentRepository90/Rules/NodeTypeGetNameRector.php
- tests/ContentRepository90/Rules/FusionNodeTypeNameRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeTypeNameRector/FusionNodeTypeNameRectorTest.php
- tests/ContentRepository90/Rules/FusionNodeTypeNameRector/config/configured_rule.php
- tests/Rules/NodeTypeGetNameRector/Fixture/all.php.inc
- tests/Rules/NodeTypeGetNameRector/NodeTypeGetNameRectorTest.php
- tests/Rules/NodeTypeGetNameRector/config/configured_rule.php
Rector migration for `NodeType::getName` removal
https://github.com/neos/neos-development-collection/issues/4560
**PHP**
`$nodeType->getName()` to `$nodeType->name->value`
**Fusion**
`${node.nodeType.name}` to `${node.nodeTypeName.value}`
Fixes partly #25
> FEATURE: Rewrite NodeType::getName()

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionContextCurrentRenderingModeRector.php
- tests/ContentRepository90/Rules/FusionContextCurrentRenderingModeRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionContextCurrentRenderingModeRector/FusionContextCurrentRenderingModeRectorTest.php
- tests/ContentRepository90/Rules/FusionContextCurrentRenderingModeRector/config/configured_rule.php
Statements accessing using`(node|documentNode|site).context.currentRenderingMode.(edit|preview|name|title|fusionPath|options)` are migrated. Other uses of `context.currentRenderingMode` are marked with a comment.
Resolves: #23
> TASK: Migrate fusion `context.currentRenderingMode` statements

- src/ContentRepository90/Rules/FusionNodeParentRector.php
- tests/ContentRepository90/Rules/FusionNodeParentRector/Fixture/some_file.fusion.inc
> BUGFIX: Replace fusion node.parent with proper FlowQuery

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionPrimaryContentRector.php
- tests/ContentRepository90/Rules/FusionPrimaryContentRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionPrimaryContentRector/Fixture/some_file2.fusion.inc
- tests/ContentRepository90/Rules/FusionPrimaryContentRector/FusionPrimaryContentRectorTest.php
- tests/ContentRepository90/Rules/FusionPrimaryContentRector/config/configured_rule.php
Adds a warning to each Fusion file containing `Neos.Neos:PrimaryContent`
See: https://github.com/neos/neos-development-collection/pull/4281
See: https://github.com/neos/neos-development-collection/issues/4622
> TASK PrimaryContent removal

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeHiddenAfterDateTimeRector.php
- src/ContentRepository90/Rules/FusionNodeHiddenBeforeDateTimeRector.php
- tests/ContentRepository90/Rules/FusionNodeHiddenAfterDateTimeRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeHiddenAfterDateTimeRector/FusionNodeHiddenAfterDateTimeRectorTest.php
- tests/ContentRepository90/Rules/FusionNodeHiddenAfterDateTimeRector/config/configured_rule.php
- tests/ContentRepository90/Rules/FusionNodeHiddenBeforeDateTimeRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeHiddenBeforeDateTimeRector/FusionNodeHiddenBeforeDateTimeRectorTest.php
- tests/ContentRepository90/Rules/FusionNodeHiddenBeforeDateTimeRector/config/configured_rule.php
Fusion: 
* Rewrite `node.hiddenBeforeDateTime` to `q(node).property("enableAfterDateTime")`
* Rewrite `q(node).property("_hiddenBeforeDateTime")` to `q(node).property("enableAfterDateTime")`
* Rewrite `node.hiddenAfterDateTime` to `q(node).property("disableAfterDateTime")`
* Rewrite `q(node).property("_hiddenAfterDateTime")` to `q(node).property("disableAfterDateTime")`
Fixes #41
> FEATURE: Migration for new fusion property access of timeable node visibility

- config/set/contentrepository-90.php
- src/Generic/Rules/FusionReplacePrototypeNameRector.php
- src/Generic/ValueObject/FusionPrototypeNameReplacement.php
- tests/Generic/Rules/FusionPrototypeNameReplacement/Fixture/some_file.fusion.inc
- tests/Generic/Rules/FusionPrototypeNameReplacement/config/configured_rule.php
* Add rule for adding comments to Prototype name replacements.
* Add comment for Neos.Fusion:Collection =>Neos.Fusion:Loop
* Add comment for Neos.Fusion:RawCollection => Neos.Fusion:Map
> Add comments for FusionReplacePrototypeNameRector if needed

- config/set/contentrepository-90.php
- src/Generic/Rules/FusionPrototypeNameAddCommentRector.php
> BUGFIX: Fix error with rule configuration

- config/set/contentrepository-90.php
... at least partially ... to 100% equivalent would be to cast that to a string now but idk how.
```
NodeName::fromString($stuff)->value;
```
> TASK: Correctly migrate Neos\ContentRepository\Utility

- src/ContentRepository90/Rules/FusionNodeContextPathRector.php
- src/ContentRepository90/Rules/FusionNodeDepthRector.php
- src/ContentRepository90/Rules/FusionNodeHiddenInIndexRector.php
- src/ContentRepository90/Rules/FusionNodePathRector.php
- tests/ContentRepository90/Rules/FusionNodeContextPathRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeDepthRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeHiddenInIndexRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodePathRector/Fixture/some_file.fusion.inc
Also fixed existing and added missing tests.
* _contextPath
* _depth
* _hiddenInIndex
* _path
> BUGFIX Rewrite of internal node properties in FlowQueries

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeNodeTypeRector.php
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_getter.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_nodeTypeName_flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_nodeTypeName_getter.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/FusionNodeNodeTypeRectorTest.php
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/config/configured_rule.php
Solves partially https://github.com/neos/rector/issues/57
Also migrates `q(node).property('_nodeType.name')` as we actually used the syntax once as well: https://github.com/neos/neos-development-collection/pull/3641
> TASK: Migrate `${node.nodeType.name}` and `${node.nodeType}`

- config/set/contentrepository-90.php
- src/Generic/Rules/FusionReplacePrototypeNameRector.php
- src/Generic/ValueObject/FusionPrototypeNameReplacement.php
- tests/Generic/Rules/FusionPrototypeNameReplacement/Fixture/skip_prototype_definition.fusion.inc
- tests/Generic/Rules/FusionPrototypeNameReplacement/Fixture/some_file.fusion.inc
- tests/Generic/Rules/FusionPrototypeNameReplacement/config/configured_rule.php
- tests/Sets/ContentRepository90/ContentRepository90Test.php
- tests/Sets/ContentRepository90/Fixture/baseline.fusion.inc
- tests/Sets/ContentRepository90/Fixture/primary-content.fusion.inc
Adjusts the set such that usages of `Neos.Neos:PrimaryContent` are replaced while overrides are still kept
Resolves: #78
Related: #79
> TASK: Replace usages of `Neos.Neos:PrimaryContent`

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/NodeLabelGeneratorRector.php
- tests/ContentRepository90/Rules/NodeLabelGeneratorRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeLabelGeneratorRector/NodeLabelGeneratorRectorTest.php
- tests/ContentRepository90/Rules/NodeLabelGeneratorRector/config/configured_rule.php
> TASK: Add migration for getLabel with NodeLabelGeneratorRector

- config/set/contentrepository-90.php
… as this is not available anymore
> BUGFIX: Remove rule for rewriting Node::getNodeType to Node::nodeType

- config/set/contentrepository-90.php
- tests/Sets/ContentRepository90/ContentRepository90Test.php
- tests/Sets/ContentRepository90/Fixture/rename-node-interface-classes.php.inc
This fix re-enables the class renaming of e.g. the NodeInterface. 
Also added a testcase ensure this is working.
> BUGFIX: Configure each rule once, as multiple definitions just override the previous ones

- config/set/contentrepository-90.php
- src/Generic/Rules/SignalSlotToWarningCommentRector.php
- src/Generic/ValueObject/SignalSlotToWarningComment.php
- tests/Generic/Rules/SignalSlotToWarningCommentRector/Fixture/some_class.php.inc
- tests/Generic/Rules/SignalSlotToWarningCommentRector/SignalSlotToWarningCommentRectorTest.php
- tests/Generic/Rules/SignalSlotToWarningCommentRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/Signals/Context.php.inc
- tests/Sets/ContentRepository90/Fixture/Signals/Node.php.inc
- tests/Sets/ContentRepository90/Fixture/Signals/NodeData.php.inc
- tests/Sets/ContentRepository90/Fixture/Signals/NodeDataRepository.php.inc
- tests/Sets/ContentRepository90/Fixture/Signals/PublishingService.php.inc
- tests/Sets/ContentRepository90/Fixture/Signals/Workspace.php.inc
Fixes #48 
Adds warnings for all removed signals:
**Neos\ContentRepository\Domain\Model\Node**
* beforeNodeMove
* afterNodeMove
* beforeNodeCopy
* afterNodeCopy
* nodePathChanged
* beforeNodeCreate
* afterNodeCreate
* nodeAdded
* nodeUpdated
* nodeRemoved
* beforeNodePropertyChange
* nodePropertyChanged
**Neos\ContentRepository\Domain\Model\NodeData**
* nodePathChanged
**Neos\ContentRepository\Domain\Model\Workspace**
* baseWorkspaceChanged
* beforeNodePublishing
* afterNodePublishing
**Neos\ContentRepository\Domain\Repository\NodeDataRepository**
* repositoryObjectsPersisted
**Neos\ContentRepository\Domain\Service\Context**
* beforeAdoptNode
* afterAdoptNode
**Neos\ContentRepository\Domain\Service\PublishingService**
* nodePublished
* nodeDiscarded
> FEATURE: Add warnings for removed signals

- config/set/contentrepository-90.php
- docs/rules_overview.md
- src/ContentRepository90/Rules/NodeSearchServiceRector.php
- tests/ContentRepository90/Rules/NodeSearchServiceRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeSearchServiceRector/NodeSearchServiceRectorTest.php
- tests/ContentRepository90/Rules/NodeSearchServiceRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/node-search-service.php.inc
> FEATURE: Add migration for NodeSearchService

- config/set/contentrepository-90.php
- src/Generic/Rules/SignalSlotToWarningCommentRector.php
- tests/Sets/ContentRepository90/Fixture/Signals/PublishingService.php.inc
Add `Neos\Neos\Service\PublishingService` also to list of removed signals slots.
Usually this should be covered by parent class `Neos\ContentRepository\Domain\Service\PublishingService`. But as these classes doesn't exists anymore in the new code base, rector is not able to determine that.
> TASK: Improve signal slot handling for PublishingService

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionContextGetWorkspaceNameRector.php
- src/ContentRepository90/Rules/FusionContextGetWorkspaceRector.php
- tests/ContentRepository90/Rules/FusionContextGetWorkspaceNameRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionContextGetWorkspaceNameRector/FusionContextGetWorkspaceNameRectorTest.php
- tests/ContentRepository90/Rules/FusionContextGetWorkspaceNameRector/config/configured_rule.php
- tests/ContentRepository90/Rules/FusionContextGetWorkspaceRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionContextGetWorkspaceRector/FusionContextGetWorkspaceRectorTest.php
- tests/ContentRepository90/Rules/FusionContextGetWorkspaceRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/Context/content-context.fusion.inc
- tests/Sets/ContentRepository90/Fixture/Context/context-current-rendering-mode.fusion.inc
- tests/Sets/ContentRepository90/Fixture/Context/context-current-site.fusion.inc
- tests/Sets/ContentRepository90/Fixture/Context/context.fusion.inc
> FEATURE: Improve context rewrites in fusion

- src/ContentRepository90/Rules/ContextGetRootNodeRector.php
- src/ContentRepository90/Rules/NodeGetContextGetWorkspaceNameRector.php
- src/ContentRepository90/Rules/NodeGetContextGetWorkspaceRector.php
- src/ContentRepository90/Rules/Traits/ContentRepositoryTrait.php
- src/ContentRepository90/Rules/Traits/NodeTrait.php
- src/ContentRepository90/Rules/WorkspaceRepositoryCountByNameRector.php
- tests/ContentRepository90/Rules/WorkspaceRepositoryCountByNameRector/Fixture/some_class.php.inc
- tests/Rules/ContextGetRootNodeRector/Fixture/some_class.php.inc
- tests/Rules/NodeGetContextGetWorkspaceNameRector/Fixture/some_class.php.inc
- tests/Rules/NodeGetContextGetWorkspaceRector/Fixture/some_class.php.inc
This PR updates some older migrations to the current state of Neos 9. 
* Removed `Node->subgraphIdentity`
* Removed `contentStreamId` based access to nodes
* Removed `WorkspaceFinder`
* Added usage of new `Node` properties (contentRepositoryId, workspaceName, ...?
* Updated visibility constraints `frontend` => `default`
Fixes: #129 #130
> TASK: Update migrations to current state of Neos 9

- docs/rules_overview.md
- src/ContentRepository90/Rules/NodeIsHiddenRector.php
- tests/Rules/NodeIsHiddenRector/Fixture/some_class.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-hidden.php.inc
As `SubtreeTag::disabled()` is deprecated, we should directly refactor to `NeosSubtreeTag::disabled()`
> TASK: Refactor SubtreeTag references to NeosSubtreeTag.

- config/set/contentrepository-90.php
This has been changed in meanwhile from `Node::nodeAggregateId` to `Node::aggregateId`
> TASK: Rename property for replacement from `nodeAggregateId` to `aggregateId`
