- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeHiddenInIndexRector.php
- src/ContentRepository90/Rules/NodeIsHiddenInIndexRector.php
- tests/ContentRepository90/Rules/FusionNodeHiddenInIndexRector/Fixture/some_file.fusion
- tests/ContentRepository90/Rules/FusionNodeHiddenInIndexRector/FusionNodeHiddenInIndexRectorTest.php
- tests/ContentRepository90/Rules/FusionNodeHiddenInIndexRector/config/configured_rule.php
- tests/ContentRepository90/Rules/NodeIsHiddenInIndexRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeIsHiddenInIndexRector/NodeIsHiddenInIndexRectorTest.php
- tests/ContentRepository90/Rules/NodeIsHiddenInIndexRector/config/configured_rule.php
NodeIsHiddenInIndexRector migrates
`$node->isHiddenInIndex();`
to
`$node->getProperty('_hiddenInIndex');`
FusionNodeHiddenInIndexRector migrates
`node.hiddenInIndex`
to
`node.properties._hiddenInIndex`
> FEATURE: add rectors NodeIsHiddenInIndexRector and FusionNodeHiddenInIndexRector

- tests/Generic/Rules/FusionNodePropertyPathToWarningCommentRector/Fixture/some_file.fusion
- tests/Generic/Rules/FusionNodePropertyPathToWarningCommentRector/config/configured_rule.php
Within fusion we have to omit get* and is*.
> BUGFIX: fix fusion property names within test

- .github/workflows/build.yml
The composer tests are run for main and every pr targeted to main.
> TASK: Add github workflow to run composer test

- src/ContentRepository90/Rules/NodeGetChildNodesRector.php
- src/ContentRepository90/Rules/Traits/SubgraphTrait.php
- tests/Rules/NodeGetChildNodesRector/Fixture/all-with-pagination-named-arguments.php.inc
- tests/Rules/NodeGetChildNodesRector/Fixture/all-with-pagination.php.inc
- tests/Rules/NodeGetChildNodesRector/Fixture/all.php.inc
- tests/Rules/NodeGetChildNodesRector/Fixture/nodetype-filter-with-pagination.php.inc
- tests/Rules/NodeGetChildNodesRector/Fixture/nodetype-filter.php.inc
Due to the latest changes to FindChildNodesFilter
> BUGFIX: Refactor Node::getChildNodes rector refactoring 

- src/ContentRepository90/Rules/FusionNodeParentRector.php
- tests/ContentRepository90/Rules/FusionNodeParentRector/Fixture/some_file.fusion.inc
> BUGFIX: No longer warn for node.parents()

- config/set/contentrepository-90.php
- src/ContentRepository90/Legacy/NodeLegacyStub.php
- src/ContentRepository90/Rules/NodeTypeAllowsGrandchildNodeTypeRector.php
- src/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodesRector.php
- src/ContentRepository90/Rules/NodeTypeGetTypeOfAutoCreatedChildNodeRector.php
- tests/ContentRepository90/Rules/NodeTypeAllowsGrandchildNodeType/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeTypeAllowsGrandchildNodeType/NodeTypeAllowsGrandchildNodeTypeTest.php
- tests/ContentRepository90/Rules/NodeTypeAllowsGrandchildNodeType/config/configured_rule.php
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/Fixture/some_class2.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/Fixture/some_class3.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/Fixture/some_class4.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/Fixture/some_class5.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/NodeTypeGetAutoCreatedChildNodesTest.php
- tests/ContentRepository90/Rules/NodeTypeGetAutoCreatedChildNodes/config/configured_rule.php
- tests/ContentRepository90/Rules/NodeTypeGetTypeOfAutoCreatedChildNode/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetTypeOfAutoCreatedChildNode/Fixture/some_class2.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetTypeOfAutoCreatedChildNode/Fixture/some_class3.php.inc
- tests/ContentRepository90/Rules/NodeTypeGetTypeOfAutoCreatedChildNode/NodeTypeGetTypeOfAutoCreatedChildNodeTest.php
- tests/ContentRepository90/Rules/NodeTypeGetTypeOfAutoCreatedChildNode/config/configured_rule.php
> TASK: Refactor nodetype

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeAggregateIdentifierRector.php
- src/ContentRepository90/Rules/FusionNodeIdentifierRector.php
- tests/ContentRepository90/Rules/FusionNodeIdentifierRector/Fixture/flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeIdentifierRector/Fixture/node_getter.fusion.inc
> Change rewrite of node.identifier and q(node).property('identifier') to new q(node).id()

- config/set/contentrepository-90.php
Fixes some incorrect FQNs and streamline the rest to use class constant
> BUGFIX Use ::class constant for class names

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeLabelRector.php
- tests/ContentRepository90/Rules/FusionNodeLabelRector/Fixture/flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeLabelRector/Fixture/node_getter.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeLabelRector/FusionNodeLabelRectorTest.php
- tests/ContentRepository90/Rules/FusionNodeLabelRector/config/configured_rule.php
Solves partially https://github.com/neos/rector/issues/71
> TASK: Migrate `${node.label}` to `${q(node).label()}`

- src/ContentRepository90/Rules/FusionNodeHiddenInIndexRector.php
- src/ContentRepository90/Rules/NodeIsHiddenInIndexRector.php
- tests/ContentRepository90/Rules/FusionNodeHiddenInIndexRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/NodeIsHiddenInIndexRector/Fixture/some_class.php.inc
Resolves: #65
See core change https://github.com/neos/neos-development-collection/pull/4921
> BUGFIX: #65 migrate hiddenInMenu correctly

- README.md
Update the install instructions to install neos/rector in a dedicated project/directory inside of the distribution.
> TASK: Update install instructions

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeTypeNameRector.php
- tests/ContentRepository90/Rules/FusionNodeTypeNameRector/Fixture/some_file.fusion.inc
See: https://discuss.neos.io/t/neos-9-beta-14-release/6648
Some cases are already handled in other PRs.
> TASK: Remove .value in Fusion migrations

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeAggregateIdentifierRector.php
- src/ContentRepository90/Rules/FusionNodeIdentifierRector.php
- src/ContentRepository90/Rules/FusionNodeLabelRector.php
- src/ContentRepository90/Rules/FusionNodeNodeTypeRector.php
- tests/ContentRepository90/Rules/FusionNodeAggregateIdentifierRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeIdentifierRector/Fixture/flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeIdentifierRector/Fixture/node_getter.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeLabelRector/Fixture/flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeLabelRector/Fixture/node_getter.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_nodeTypeName_flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_nodeTypeName_getter.fusion.inc
> TASK: Remove deprecated FlowQuery usages and use node field access instead

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionNodeNodeTypeRector.php
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/flow_query_property.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_getter.fusion.inc
- tests/ContentRepository90/Rules/FusionNodeNodeTypeRector/Fixture/node_nodeTypeName_getter.fusion.inc
See: https://discuss.neos.io/t/neos-9-beta-14-release/6648
> TASK: Replace Neos.Node.getNodeType() with Neos.Node.nodeType()

- config/set/contentrepository-90.php
- docs/rules_overview.md
- src/ContentRepository90/Rules/NodeGetContextGetWorkspaceNameRector.php
- src/ContentRepository90/Rules/NodeGetContextPathRector.php
- src/ContentRepository90/Rules/NodeGetDimensionsRector.php
- src/ContentRepository90/Rules/NodeGetHiddenBeforeAfterDateTimeRector.php
- src/ContentRepository90/Rules/NodeIsAutoCreatedRector.php
- tests/ContentRepository90/Rules/NodeGetContextPathRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeGetContextPathRector/NodeGetContextPathRectorTest.php
- tests/ContentRepository90/Rules/NodeGetContextPathRector/config/configured_rule.php
- tests/ContentRepository90/Rules/NodeGetHiddenBeforeAfterDateTimeRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeGetHiddenBeforeAfterDateTimeRector/NodeGetHiddenBeforeAfterDateTimeRectorTest.php
- tests/ContentRepository90/Rules/NodeGetHiddenBeforeAfterDateTimeRector/config/configured_rule.php
- tests/ContentRepository90/Rules/NodeIsAutoCreatedRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/NodeIsAutoCreatedRector/NodeIsAutoCreatedRectorTest.php
- tests/ContentRepository90/Rules/NodeIsAutoCreatedRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/Node/node-auto-created.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-copy.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-get-context-path.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-hidden-before-after-date-time.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-hidden.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-move.php.inc
- tests/Sets/ContentRepository90/Fixture/Node/node-remove.php.inc
See also: #95
Related: https://github.com/neos/rector/issues/75
> FEATURE: Improve Node and Node interfaces rewrites (part 2)

- src/ContentRepository90/Rules/FusionContextCurrentSiteRector.php
- tests/Sets/ContentRepository90/Fixture/Context/context-current-site.fusion.inc
> BUGFIX: Prevent replacing of context.currentSiteNode

- config/set/contentrepository-90.php
- tests/Sets/ContentRepository90/Fixture/inject-removal.php.inc
> FEATURE: Remove injections of removed services

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionCacheLifetimeRector.php
- tests/ContentRepository90/Rules/FusionCacheLifetimeRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionCacheLifetimeRector/FusionCacheLifetimeRectorTest.php
- tests/ContentRepository90/Rules/FusionCacheLifetimeRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/Fusion/cache-lifetime.fusion.inc
> FEATURE: Add comment on usage of cacheLifetime in Fusion

- composer.json
The 0.15.25 contains compatible changes with our rector implementation and also a fix for broken trait detection.
> TASK: Update Rector to 0.15.25

- config/set/contentrepository-90.php
- src/Generic/Rules/MethodCallToWarningCommentRector.php
- tests/Rules/MethodCallToWarningCommentRector/Fixture/some_class.php.inc
- tests/Rules/MethodCallToWarningCommentRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/node-data.php.inc
> FEATURE: Add todo warnings for all NodeData::* methods

- composer.json
- config/set/contentrepository-90.php
- src/ContentRepository90/Legacy/CreateContentContextTrait.php
- tests/Sets/ContentRepository90/Fixture/Context/create-content-context.php.inc
> FEATURE: Remove CreateContentContextTrait and add todos

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/FusionFlowQueryContextRector.php
- tests/ContentRepository90/Rules/FusionFlowQueryContextRector/Fixture/some_file.fusion.inc
- tests/ContentRepository90/Rules/FusionFlowQueryContextRector/FusionQueryContextRectorTest.php
- tests/ContentRepository90/Rules/FusionFlowQueryContextRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/Fusion/flow-query-context.fusion.inc
> FEATURE: Add comments when removed properties are used in the FlowQuery operation context.

- config/set/contentrepository-90.php
- src/ContentRepository90/Rules/Traits/ContentRepositoryTrait.php
- src/ContentRepository90/Rules/WorkspaceRepositoryFindByBaseWorkspaceRector.php
- src/ContentRepository90/Rules/WorkspaceRepositoryFindByIdentifierRector.php
- tests/ContentRepository90/Rules/WorkspaceRepositoryCountByNameRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/WorkspaceRepositoryFindByBaseWorkspaceRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/WorkspaceRepositoryFindByBaseWorkspaceRector/WorkspaceRepositoryFindByIdentifierRectorTest.php
- tests/ContentRepository90/Rules/WorkspaceRepositoryFindByBaseWorkspaceRector/config/configured_rule.php
- tests/ContentRepository90/Rules/WorkspaceRepositoryFindByIdentifierRector/Fixture/some_class.php.inc
- tests/ContentRepository90/Rules/WorkspaceRepositoryFindByIdentifierRector/WorkspaceRepositoryFindByBaseWorkspaceRectorTest.php
- tests/ContentRepository90/Rules/WorkspaceRepositoryFindByIdentifierRector/config/configured_rule.php
- tests/Sets/ContentRepository90/Fixture/Workspace/workspace-repository.php.inc
> FEATURE: Add migration for removed WorkspaceRepository

- composer.json
> Add PHP dependency to avoid PHP 8.4
